// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package dht

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DHTMessage_MessageType int32

const (
	DHTMessage_PUT_VALUE     DHTMessage_MessageType = 0
	DHTMessage_GET_VALUE     DHTMessage_MessageType = 1
	DHTMessage_ADD_PROVIDER  DHTMessage_MessageType = 2
	DHTMessage_GET_PROVIDERS DHTMessage_MessageType = 3
	// Unique ID of this message, used to match queries with responses
	DHTMessage_FIND_NODE DHTMessage_MessageType = 4
	// Signals whether or not this message is a response to another message
	DHTMessage_PING DHTMessage_MessageType = 5
)

var DHTMessage_MessageType_name = map[int32]string{
	0: "PUT_VALUE",
	1: "GET_VALUE",
	2: "ADD_PROVIDER",
	3: "GET_PROVIDERS",
	4: "FIND_NODE",
	5: "PING",
}
var DHTMessage_MessageType_value = map[string]int32{
	"PUT_VALUE":     0,
	"GET_VALUE":     1,
	"ADD_PROVIDER":  2,
	"GET_PROVIDERS": 3,
	"FIND_NODE":     4,
	"PING":          5,
}

func (x DHTMessage_MessageType) Enum() *DHTMessage_MessageType {
	p := new(DHTMessage_MessageType)
	*p = x
	return p
}
func (x DHTMessage_MessageType) String() string {
	return proto.EnumName(DHTMessage_MessageType_name, int32(x))
}
func (x *DHTMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DHTMessage_MessageType_value, data, "DHTMessage_MessageType")
	if err != nil {
		return err
	}
	*x = DHTMessage_MessageType(value)
	return nil
}
func (DHTMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_65e0fd3bdb20de98, []int{0, 0}
}

type DHTMessage struct {
	Type  *DHTMessage_MessageType `protobuf:"varint,1,req,name=type,enum=dht.DHTMessage_MessageType" json:"type,omitempty"`
	Key   *string                 `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value []byte                  `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	// Unique ID of this message, used to match queries with responses
	Id *uint64 `protobuf:"varint,4,req,name=id" json:"id,omitempty"`
	// Signals whether or not this message is a response to another message
	Response             *bool    `protobuf:"varint,5,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTMessage) Reset()         { *m = DHTMessage{} }
func (m *DHTMessage) String() string { return proto.CompactTextString(m) }
func (*DHTMessage) ProtoMessage()    {}
func (*DHTMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_65e0fd3bdb20de98, []int{0}
}
func (m *DHTMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTMessage.Unmarshal(m, b)
}
func (m *DHTMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTMessage.Marshal(b, m, deterministic)
}
func (dst *DHTMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTMessage.Merge(dst, src)
}
func (m *DHTMessage) XXX_Size() int {
	return xxx_messageInfo_DHTMessage.Size(m)
}
func (m *DHTMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DHTMessage proto.InternalMessageInfo

func (m *DHTMessage) GetType() DHTMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DHTMessage_PUT_VALUE
}

func (m *DHTMessage) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DHTMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DHTMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DHTMessage) GetResponse() bool {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return false
}

func init() {
	proto.RegisterType((*DHTMessage)(nil), "dht.DHTMessage")
	proto.RegisterEnum("dht.DHTMessage_MessageType", DHTMessage_MessageType_name, DHTMessage_MessageType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_65e0fd3bdb20de98) }

var fileDescriptor_messages_65e0fd3bdb20de98 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xcd, 0x06, 0xd2, 0xb1, 0x0d, 0xeb, 0xe0, 0x61, 0xd1, 0xcb, 0xd2, 0xd3, 0x9e,
	0x22, 0xf8, 0x0f, 0x0a, 0x1b, 0x6b, 0x40, 0xd3, 0xb0, 0xa6, 0xbd, 0x86, 0x42, 0x06, 0x1b, 0xfc,
	0x48, 0xe8, 0x46, 0x21, 0xff, 0xdd, 0x83, 0xc4, 0x5a, 0xed, 0x69, 0xe6, 0x99, 0xf7, 0x19, 0x5e,
	0x88, 0xdf, 0xc8, 0xfb, 0xed, 0x33, 0xf9, 0xa4, 0xdb, 0xb7, 0x7d, 0x8b, 0x41, 0xbd, 0xeb, 0xe7,
	0x5f, 0x0c, 0xc0, 0xde, 0x97, 0x8f, 0x87, 0x08, 0x6f, 0x40, 0xf4, 0x43, 0x47, 0x8a, 0x69, 0x6e,
	0xe2, 0xdb, 0xeb, 0xa4, 0xde, 0xf5, 0xc9, 0x7f, 0x9c, 0xfc, 0xce, 0x72, 0xe8, 0xc8, 0xfd, 0x88,
	0x28, 0x21, 0x78, 0xa1, 0x41, 0x71, 0xcd, 0xcc, 0xc4, 0x8d, 0x2b, 0x5e, 0x42, 0xf8, 0xb9, 0x7d,
	0xfd, 0x20, 0x15, 0x68, 0x66, 0xa6, 0xee, 0x00, 0x18, 0x03, 0x6f, 0x6a, 0x25, 0x34, 0x37, 0xc2,
	0xf1, 0xa6, 0xc6, 0x2b, 0x88, 0xf6, 0xe4, 0xbb, 0xf6, 0xdd, 0x93, 0x0a, 0x35, 0x33, 0x91, 0xfb,
	0xe3, 0x79, 0x03, 0xe7, 0x27, 0x45, 0x38, 0x83, 0x49, 0xb1, 0x2e, 0xab, 0xcd, 0xe2, 0x61, 0x9d,
	0xca, 0xb3, 0x11, 0x97, 0xe9, 0x11, 0x19, 0x4a, 0x98, 0x2e, 0xac, 0xad, 0x0a, 0xb7, 0xda, 0x64,
	0x36, 0x75, 0x92, 0xe3, 0x05, 0xcc, 0x46, 0xe1, 0x78, 0x79, 0x92, 0xc1, 0xf8, 0x73, 0x97, 0xe5,
	0xb6, 0xca, 0x57, 0x36, 0x95, 0x02, 0x23, 0x10, 0x45, 0x96, 0x2f, 0x65, 0xf8, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x5c, 0xa6, 0x8d, 0x14, 0x01, 0x00, 0x00,
}
